config/routes.rb
Rails.application.routes.draw do
  resources :ftpfiles
  resources :ftpcrs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/sftp_helper.rb
module SftpHelper
	def sftp_copy_files(source_folder = '/', options = {})
		return nil unless source_folder.first == '/'
		source_folder += '/' unless source_folder[-1, 1] == '/'
		sftp_save_files(source_folder, default_destination_folder + source_folder, options[:folders])
		sftp_close
	end

	def sftp
		@session ||= Net::SSH.start(self.ip, self.username, {password: self.password, port: 22})
		@sftp ||= Net::SFTP::Session.new(@session)
		@sftp.connect! unless @sftp.open?
		@sftp
	end
	def sftp_close
		@sftp.close_channel unless @sftp.nil? # Close SFTP
  		@session.close unless @session.nil?
	end
	def sftp_save_files(source_folder, destination_folder, folders = false)
		FileUtils.mkdir_p(destination_folder) unless Dir.exist?(destination_folder)
		begin
			entries = sftp.dir.entries(source_folder)
		rescue Exception => e
			p "%%%%%%%%%%%%%%%%%%%%"
			p "path => #{source_folder}"
			p e.message
			p "%%%%%%%%%%%%%%%%%%%%"
			return nil
		end
		entries.each do |entry|
			if entry.file?
				save_file_with_sftp(source_folder + entry.name, destination_folder + entry.name)
			elsif folders && entry.name != '.' && entry.name != '..'
				sftp_save_files(source_folder + entry.name + '/', destination_folder + entry.name + '/', true)
			end
		end
	end

	def save_file_with_sftp(source_file, destination_file)
		begin
			if ftpfiles.where(file_name: source_file).blank?
				sftp.download!(source_file, destination_file)
				ftpfiles.create(file_name: source_file)
			end
		rescue Exception => e
			p "%%%%%%%%%%%%%%%%%%%%"
			p "file => #{source_file}"
			p e.message
			p "%%%%%%%%%%%%%%%%%%%%"
		end
	end
end

app/models/ftpcr.rb
require 'net/ftp'
class Ftpcr < ApplicationRecord
	include SftpHelper

	has_many :ftpfiles, dependent: :destroy
	validates_uniqueness_of :ip, scope: :username
	
	def default_destination_folder
		Rails.root.join('public', 'ftp', ip.gsub(/[^0-9A-Z]/i, '_')).to_s
	end
	def self.trigger_copying_all
		self.all.each{|ftpcr| ftpcr.sftp_copy_files}
	end
end

app/models/ftpfile.rb
class Ftpfile < ApplicationRecord
  belongs_to :ftpcr
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ftpcrs_controller.rb
class FtpcrsController < ApplicationController
  before_action :set_ftpcr, only: [:show, :edit, :update, :destroy]

  # GET /ftpcrs
  # GET /ftpcrs.json
  def index
    @ftpcrs = Ftpcr.all
  end

  # GET /ftpcrs/1
  # GET /ftpcrs/1.json
  def show
  end

  # GET /ftpcrs/new
  def new
    @ftpcr = Ftpcr.new
  end

  # GET /ftpcrs/1/edit
  def edit
  end

  # POST /ftpcrs
  # POST /ftpcrs.json
  def create
    @ftpcr = Ftpcr.new(ftpcr_params)

    respond_to do |format|
      if @ftpcr.save
        format.html { redirect_to @ftpcr, notice: 'Ftpcr was successfully created.' }
        format.json { render :show, status: :created, location: @ftpcr }
      else
        format.html { render :new }
        format.json { render json: @ftpcr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ftpcrs/1
  # PATCH/PUT /ftpcrs/1.json
  def update
    respond_to do |format|
      if @ftpcr.update(ftpcr_params)
        format.html { redirect_to @ftpcr, notice: 'Ftpcr was successfully updated.' }
        format.json { render :show, status: :ok, location: @ftpcr }
      else
        format.html { render :edit }
        format.json { render json: @ftpcr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ftpcrs/1
  # DELETE /ftpcrs/1.json
  def destroy
    @ftpcr.destroy
    respond_to do |format|
      format.html { redirect_to ftpcrs_url, notice: 'Ftpcr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ftpcr
      @ftpcr = Ftpcr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ftpcr_params
      params.require(:ftpcr).permit(:ip, :username, :password, :source_location)
    end
end

app/controllers/ftpfiles_controller.rb
class FtpfilesController < ApplicationController
  before_action :set_ftpfile, only: [:show, :edit, :update, :destroy]

  # GET /ftpfiles
  # GET /ftpfiles.json
  def index
    @ftpfiles = Ftpfile.all
  end

  # GET /ftpfiles/1
  # GET /ftpfiles/1.json
  def show
  end

  # GET /ftpfiles/new
  def new
    @ftpfile = Ftpfile.new
  end

  # GET /ftpfiles/1/edit
  def edit
  end

  # POST /ftpfiles
  # POST /ftpfiles.json
  def create
    @ftpfile = Ftpfile.new(ftpfile_params)

    respond_to do |format|
      if @ftpfile.save
        format.html { redirect_to @ftpfile, notice: 'Ftpfile was successfully created.' }
        format.json { render :show, status: :created, location: @ftpfile }
      else
        format.html { render :new }
        format.json { render json: @ftpfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ftpfiles/1
  # PATCH/PUT /ftpfiles/1.json
  def update
    respond_to do |format|
      if @ftpfile.update(ftpfile_params)
        format.html { redirect_to @ftpfile, notice: 'Ftpfile was successfully updated.' }
        format.json { render :show, status: :ok, location: @ftpfile }
      else
        format.html { render :edit }
        format.json { render json: @ftpfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ftpfiles/1
  # DELETE /ftpfiles/1.json
  def destroy
    @ftpfile.destroy
    respond_to do |format|
      format.html { redirect_to ftpfiles_url, notice: 'Ftpfile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ftpfile
      @ftpfile = Ftpfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ftpfile_params
      params.require(:ftpfile).permit(:ftpcr_id, :file_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ftpcrs_helper.rb
module FtpcrsHelper
end

app/helpers/ftpfiles_helper.rb
module FtpfilesHelper
end

app/views/ftpcrs/_form.html.erb
<%= form_with(model: ftpcr, local: true) do |form| %>
  <% if ftpcr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ftpcr.errors.count, "error") %> prohibited this ftpcr from being saved:</h2>

      <ul>
      <% ftpcr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :source_location %>
    <%= form.text_field :source_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ftpcrs/edit.html.erb
<h1>Editing Ftpcr</h1>

<%= render 'form', ftpcr: @ftpcr %>

<%= link_to 'Show', @ftpcr %> |
<%= link_to 'Back', ftpcrs_path %>

app/views/ftpcrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ftpcrs</h1>

<table>
  <thead>
    <tr>
      <th>Ip</th>
      <th>Username</th>
      <th>Password</th>
      <th>Source location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ftpcrs.each do |ftpcr| %>
      <tr>
        <td><%= ftpcr.ip %></td>
        <td><%= ftpcr.username %></td>
        <td><%= ftpcr.password %></td>
        <td><%= ftpcr.source_location %></td>
        <td><%= link_to 'Show', ftpcr %></td>
        <td><%= link_to 'Edit', edit_ftpcr_path(ftpcr) %></td>
        <td><%= link_to 'Destroy', ftpcr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ftpcr', new_ftpcr_path %>

app/views/ftpcrs/new.html.erb
<h1>New Ftpcr</h1>

<%= render 'form', ftpcr: @ftpcr %>

<%= link_to 'Back', ftpcrs_path %>

app/views/ftpcrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip:</strong>
  <%= @ftpcr.ip %>
</p>

<p>
  <strong>Username:</strong>
  <%= @ftpcr.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @ftpcr.password %>
</p>

<p>
  <strong>Source location:</strong>
  <%= @ftpcr.source_location %>
</p>

<%= link_to 'Edit', edit_ftpcr_path(@ftpcr) %> |
<%= link_to 'Back', ftpcrs_path %>

app/views/ftpfiles/_form.html.erb
<%= form_with(model: ftpfile, local: true) do |form| %>
  <% if ftpfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ftpfile.errors.count, "error") %> prohibited this ftpfile from being saved:</h2>

      <ul>
      <% ftpfile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ftpcr_id %>
    <%= form.text_field :ftpcr_id %>
  </div>

  <div class="field">
    <%= form.label :file_name %>
    <%= form.text_field :file_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ftpfiles/edit.html.erb
<h1>Editing Ftpfile</h1>

<%= render 'form', ftpfile: @ftpfile %>

<%= link_to 'Show', @ftpfile %> |
<%= link_to 'Back', ftpfiles_path %>

app/views/ftpfiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ftpfiles</h1>

<table>
  <thead>
    <tr>
      <th>Ftpcr</th>
      <th>File name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ftpfiles.each do |ftpfile| %>
      <tr>
        <td><%= ftpfile.ftpcr %></td>
        <td><%= ftpfile.file_name %></td>
        <td><%= link_to 'Show', ftpfile %></td>
        <td><%= link_to 'Edit', edit_ftpfile_path(ftpfile) %></td>
        <td><%= link_to 'Destroy', ftpfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ftpfile', new_ftpfile_path %>

app/views/ftpfiles/new.html.erb
<h1>New Ftpfile</h1>

<%= render 'form', ftpfile: @ftpfile %>

<%= link_to 'Back', ftpfiles_path %>

app/views/ftpfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ftpcr:</strong>
  <%= @ftpfile.ftpcr %>
</p>

<p>
  <strong>File name:</strong>
  <%= @ftpfile.file_name %>
</p>

<%= link_to 'Edit', edit_ftpfile_path(@ftpfile) %> |
<%= link_to 'Back', ftpfiles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ftps</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>